In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [3]:
print(my_list)

[1, 2, 3]


In [4]:
arr = np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr1 =np.array(my_mat)

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.array(range(0,11,2))

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(7)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
np.zeros((5))

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [16]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [17]:
np.linspace(2,300,10,False)

array([   2. ,   31.8,   61.6,   91.4,  121.2,  151. ,  180.8,  210.6,
        240.4,  270.2])

In [18]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [19]:
 np.random.rand(2,3)

array([[ 0.40831402,  0.3500833 ,  0.7043751 ],
       [ 0.39813128,  0.70754838,  0.83978852]])

In [20]:
np.random.randn(2,3)

array([[ 1.34886236, -1.21997876, -0.54270708],
       [ 0.57333584,  1.22044227,  0.65373532]])

In [21]:
np.random.randint(1,10, 5)

array([2, 5, 4, 7, 6])

In [22]:
np.random.randint(1,100)

99

In [23]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ran_arr = np.random.randint(1,50,10)
ran_arr

array([41, 18, 14, 47,  7, 28, 32, 24, 21, 23])

In [26]:
ran_arr.max()

47

In [27]:
ran_arr.min()

7

In [28]:
ran_arr.argmax()

3

In [29]:
ran_arr.argmin()

4

In [30]:
arr.shape

(25,)

In [31]:
row = np.arange(0,10)
print(row)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
row = row.reshape(1,10)
print(row)

[[0 1 2 3 4 5 6 7 8 9]]


In [33]:
row.shape

(1, 10)

In [34]:
row.dtype

dtype('int32')

In [15]:
arr = np.random.randint(0,100,(2,3))
arr

array([[ 6, 66, 92],
       [99, 62, 95]])

In [21]:
arr.dtype

dtype('int32')

# Slicing

In [23]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [28]:
arr[1]

1

In [29]:
arr[0:5] =100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [30]:
arr = np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
slice = arr[0:6]
slice

array([0, 1, 2, 3, 4, 5])

In [34]:
slice[[0,1,2]] = 99
slice

array([99, 99, 99,  3,  4,  5])

In [35]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_copy = np.copy(arr)
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr_copy[:6] = 99
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
bool_arr = arr>5

In [45]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [46]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Operations

In [51]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### Universal Functions

In [53]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [54]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [57]:
arr/arr

C:\Users\Mohit Uniyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [58]:
1/arr

C:\Users\Mohit Uniyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [59]:
np.log(arr)

C:\Users\Mohit Uniyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])